name: deploy preview

on:
  pull_request:
    branch:
      - main
      - dev
    types:
      - opened
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: set branch name and build directory
        id: branch_directory
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF##*/}
          echo "Branch name: $BRANCH_NAME"
          echo "Build directory: preview/$BRANCH_NAME"
          echo "::set-output name=build_directory::preview/$BRANCH_NAME"
          echo "::set-output name=build_directory_without_base::$BRANCH_NAME"

      - name: build App
        run: |
          yarn build

      - name: deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/gabrielogregorio/mfe-toolkit.git
          mkdir -p preview/${{ steps.branch_directory.outputs.build_directory }}
          cp -r dist/* preview/${{ steps.branch_directory.outputs.build_directory }}
          npx gh-pages -d preview --add -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: deploy will be done

      - name: comment on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 The deploy will be done in https://gabrielogregorio.github.io/mfe-toolkit/preview/${{ steps.branch_directory.outputs.build_directory_without_base }}/mfe-toolkit.js
          edit-mode: replace
